// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlM-MXEwThRgcgVhte0ORHYDhkXir4sPs',
    appId: '1:361469210976:android:2e8d5301e81ac999aeee05',
    messagingSenderId: '361469210976',
    projectId: 'fluttertest-77bb1',
    storageBucket: 'fluttertest-77bb1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr6G1M32-Fv5b5PWdSvgX5BDBbGR6-1pI',
    appId: '1:361469210976:ios:8d396ed784c95a04aeee05',
    messagingSenderId: '361469210976',
    projectId: 'fluttertest-77bb1',
    storageBucket: 'fluttertest-77bb1.firebasestorage.app',
    iosBundleId: 'com.orders.ordersmanagmentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr6G1M32-Fv5b5PWdSvgX5BDBbGR6-1pI',
    appId: '1:361469210976:ios:8d396ed784c95a04aeee05',
    messagingSenderId: '361469210976',
    projectId: 'fluttertest-77bb1',
    storageBucket: 'fluttertest-77bb1.firebasestorage.app',
    iosBundleId: 'com.orders.ordersmanagmentApp',
  );
}
